from .muse_character_sheet_h3 import NODE_CLASS_MAPPINGS as _H3_NODES, NODE_DISPLAY_NAME_MAPPINGS as _H3_NAMES
from .character_sheet_compositor import NODE_CLASS_MAPPINGS as _COMPOSITOR_NODES, NODE_DISPLAY_NAME_MAPPINGS as _COMPOSITOR_NAMES

WEB_DIRECTORY = "./js"

NODE_CLASS_MAPPINGS = {**_H3_NODES, **_COMPOSITOR_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_H3_NAMES, **_COMPOSITOR_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
